pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod --aot
  displayName: 'npm install and build'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: './dist'
    artifactName: 'dist'