pool:
  vmImage: 'Ubuntu 16.04'

variables:
  Version: '3.0.$(Build.BuildId)'
  ImageName: biowareru/bioengine-brc-admin:$(Version)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
      npm run build-prod
  displayName: 'npm install and build'

- script: |
    docker build . -t $(ImageName)
  displayName: 'build docker image'
  
- script: |
    docker login -u $(dockerId) -p $(dockerPswd)
  displayName: 'login to docker hub'

- script: |
    docker push $(ImageName)
  displayName: 'push image to docker hub'
