pool:
  vmImage: 'Ubuntu 16.04'

variables:
  Version: '3.0.$(Build.BuildId)'
  ImageName: :$(Version)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - task: Npm@1
    displayName: 'install npm packages'
    inputs:
      command: 'custom'
      customCommand: 'ci'

  - task: Npm@1
    displayName: 'lint files'
    inputs:
      command: 'custom'
      customCommand: 'run lint'

  - task: Npm@1
    displayName: 'build'
    inputs:
      command: 'custom'
      customCommand: 'run build-prod'

  - task: Docker@2
    displayName: 'build and push image'
    inputs:
      containerRegistry: 'BioWareRU DockerHub'
      repository: 'biowareru/bioengine-brc-admin'
      command: 'buildAndPush'
      Dockerfile: 'Dockerfile'
      buildContext: '.'
      tags: '$(Version)'
