pool:
  vmImage: 'Ubuntu 16.04'

variables:
  Version: '3.0.$(Build.BuildId)'
  ImageName: :$(Version)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
      npm ci
      npm run build-prod
  displayName: 'npm install and build'

- task: Docker@2
  displayName: 'build and push image'
  inputs:
      containerRegistry: 'BioWareRU DockerHub'
      repository: 'biowareru/bioengine-brc-admin'
      command: 'buildAndPush'
      Dockerfile: 'Dockerfile'
      buildContext: '.'
      tags: '$(Version)'
